[package]
name = "actix-upload-download"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-multipart = "0"
actix-web = "4"
derive_more = "0"
futures = "0"
sanitize-filename = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
