[workspace]

members = [
    "holodeck",
    "aar-backend",
    "aar-frontend-handlebars",
    "aar-frontend-wasm",
    "ads",
    "sas",
    "yew-tutorial",
    "news-service",
    "news-contract",
    "news-dao",
    "news-migrations",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"
