[workspace]

members = [
    "holodeck",
    "aar-backend",
    "aar-frontend-handlebars",
    "aar-frontend-wasm",
    "ads",
    "sas",
    "yew-tutorial"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"
