[workspace]
members = [
    "holodeck",
    "aar/backend",
    "aar/frontend-handlebars",
    "aar/frontend-wasm",
    "ads",
    "sas",
    "yew-tutorial",
    "news/service",
    "news/contract",
    "news/dao",
    "news/migrations",
    "tonic-example"
]
default-members = [
    "news/service"
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"
