[package]
name = "docker-simple"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.4", default-features = false, features = ["json", "rustls-tls", "blocking"] }
serde = { version = "1.0.126", features = ["derive"] }
